# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

u1 = User.create({ username: "kylesmith1", password: "jkl;'", bankroll: 1000 })
u2 = User.create({ username: "mayweather", password: "jkl;'", bankroll: 1000000 })
u3 = User.create({ username: "dbilzerian", password: "jkl;'", bankroll: 1000000000 })
u4 = User.create({ username: "guest",      password: "guest", bankroll: 10000 })


s1 = Sport.create({ name: "MLB" })
s2 = Sport.create({ name: "NFL" })
s3 = Sport.create({ name: "NBA" })
s4 = Sport.create({ name: "NCAA Football" })
s5 = Sport.create({ name: "NHL" })
s6 = Sport.create({ name: "Golf" })
s7 = Sport.create({ name: "Game of Thrones" })
s8 = Sport.create({ name: "Boxing + MMA" })
# s12 = Sport.create({ name: "App Academy" })


t1  = Team.create({ name: "Giants", city: "San Francisco", sport_id: 1 })
t2  = Team.create({ name: "Dodgers", city: "Los Angeles", sport_id: 1 })
t3  = Team.create({ name: "Yankees", city: "New York", sport_id: 1 })
t4  = Team.create({ name: "Red Sox", city: "Boston", sport_id: 1 })
t5  = Team.create({ name: "Athletics", city: "Oakland", sport_id: 1 })
t6  = Team.create({ name: "Angels", city: "Anaheim", sport_id: 1 })
t7  = Team.create({ name: "Tigers", city: "Detroit", sport_id: 1 })
t8  = Team.create({ name: "Indians", city: "Cleveland", sport_id: 1 })
t9  = Team.create({ name: "Padres", city: "San Diego", sport_id: 1 })
t10 = Team.create({ name: "Diamondbacks", city: "Arizona", sport_id: 1 })
t11 = Team.create({ name: "Mariners", city: "Seattle", sport_id: 1 })
t12 = Team.create({ name: "Rangers", city: "Texas", sport_id: 1 })
t13 = Team.create({ name: "Astros", city: "Houston", sport_id: 1 })
t14 = Team.create({ name: "Blue Jays", city: "Toronto", sport_id: 1 })
t15 = Team.create({ name: "Orioles", city: "Baltimore", sport_id: 1 })
t16 = Team.create({ name: "White Sox", city: "Chicago", sport_id: 1 })
t17 = Team.create({ name: "Rays", city: "Tampa Bay", sport_id: 1 })
t18 = Team.create({ name: "Rockies", city: "Colorado", sport_id: 1 })
t19 = Team.create({ name: "Royals", city: "Kansas City", sport_id: 1 })
t20 = Team.create({ name: "Twins", city: "Minnesota", sport_id: 1 })
t21 = Team.create({ name: "Nationals", city: "Washington", sport_id: 1 })
t22 = Team.create({ name: "Reds", city: "Cincinnati", sport_id: 1 })
t23 = Team.create({ name: "Phillies", city: "Philadelphia", sport_id: 1 })
t24 = Team.create({ name: "Marlins", city: "Miami", sport_id: 1 })
t25 = Team.create({ name: "Mets", city: "New York", sport_id: 1 })
t26 = Team.create({ name: "Cubs", city: "Chicago", sport_id: 1 })
t27 = Team.create({ name: "Cardinals", city: "St. Louis", sport_id: 1 })
t28 = Team.create({ name: "Brewers", city: "Milwaukee", sport_id: 1 })
t29 = Team.create({ name: "Pirates", city: "Pittsburgh", sport_id: 1 })
t30 = Team.create({ name: "Braves", city: "Atlanta", sport_id: 1 })

t31 = Team.create({ name: "49ers", city: "San Francisco", sport_id: 2 })
t32 = Team.create({ name: "Seahawks", city: "Seattle", sport_id: 2 })
t33 = Team.create({ name: "Giants", city: "New York", sport_id: 2 })
t34 = Team.create({ name: "Chargers", city: "San Diego", sport_id: 2 })
t35 = Team.create({ name: "Packers", city: "Green Bay", sport_id: 2 })
t36 = Team.create({ name: "Steelers", city: "Pittsburgh", sport_id: 2 })
t37 = Team.create({ name: "Cardinals", city: "Arizona", sport_id: 2 })
t38 = Team.create({ name: "Rams", city: "St. Louis", sport_id: 2 })
t39 = Team.create({ name: "Eagles", city: "Philadelphia", sport_id: 2 })
t40 = Team.create({ name: "Redskins", city: "Washington", sport_id: 2 })
t41 = Team.create({ name: "Cowboys", city: "Dallas", sport_id: 2 })
t42 = Team.create({ name: "Broncos", city: "Denver", sport_id: 2 })
t43 = Team.create({ name: "Raiders", city: "Oakland", sport_id: 2 })
t44 = Team.create({ name: "Chiefs", city: "Kansas City", sport_id: 2 })
t45 = Team.create({ name: "Bears", city: "Chicago", sport_id: 2 })
t46 = Team.create({ name: "Lions", city: "Detroit", sport_id: 2 })
t47 = Team.create({ name: "Vikings", city: "Minnesota", sport_id: 2 })
t48 = Team.create({ name: "Ravens", city: "Baltimore", sport_id: 2 })
t49 = Team.create({ name: "Bengals", city: "Cincinatti", sport_id: 2 })
t50 = Team.create({ name: "Browns", city: "Cleveland", sport_id: 2 })
t51 = Team.create({ name: "Patriots", city: "New England", sport_id: 2 })
t52 = Team.create({ name: "Dolphins", city: "Miami", sport_id: 2 })
t53 = Team.create({ name: "Jets", city: "New York", sport_id: 2 })
t54 = Team.create({ name: "Bills", city: "Buffalo", sport_id: 2 })
t55 = Team.create({ name: "Colts", city: "Indianappolis", sport_id: 2 })
t56 = Team.create({ name: "Texans", city: "Houston", sport_id: 2 })
t57 = Team.create({ name: "Jaguars", city: "Jacksonville", sport_id: 2 })
t58 = Team.create({ name: "Titans", city: "Tennessee", sport_id: 2 })
t59 = Team.create({ name: "Panthers", city: "Carolina", sport_id: 2 })
t60 = Team.create({ name: "Falcons", city: "Atlanta", sport_id: 2 })
t61 = Team.create({ name: "Buccaneers", city: "Tampa Bay", sport_id: 2 })
t62 = Team.create({ name: "Saints", city: "New Orleans", sport_id: 2 })
   
t63 = Team.create({ name: "Warriors", city: "Golden State", sport_id: 3 })
t64 = Team.create({ name: "Cavaliers", city: "Cleveland", sport_id: 3 })
t65 = Team.create({ name: "Lakers", city: "Los Angeles", sport_id: 3 })
t66 = Team.create({ name: "Knicks", city: "New York", sport_id: 3 })
t67 = Team.create({ name: "Bulls", city: "Chicago", sport_id: 3 })
t68 = Team.create({ name: "Clippers", city: "Los Angeles", sport_id: 3 })
t69 = Team.create({ name: "Heat", city: "Miami", sport_id: 3 })
t70 = Team.create({ name: "Thunder", city: "Oklahoma City", sport_id: 3 })
t71 = Team.create({ name: "Kings", city: "Sacramento", sport_id: 3 })
t72 = Team.create({ name: "Nets", city: "Brooklyn", sport_id: 3 })

t73 = Team.create({ name: "Guachos", city: "UCSB", sport_id: 4 })
t74 = Team.create({ name: "Crimson Tide", city: "Alabama", sport_id: 4 })
t75 = Team.create({ name: "Wolverines", city: "Michigan", sport_id: 4 })
t76 = Team.create({ name: "Cornhuskers", city: "Nebraska", sport_id: 4 })
t77 = Team.create({ name: "Cardinal", city: "Stanford", sport_id: 4 })
t78 = Team.create({ name: "Bears", city: "Cal", sport_id: 4 })

t79 = Team.create({ name: "Sharks", city: "San Jose", sport_id: 5 })
t80 = Team.create({ name: "Kings", city: "Los Angeles", sport_id: 5 })
t81 = Team.create({ name: "Rangers", city: "New York", sport_id: 5 })
t82 = Team.create({ name: "Red Wings", city: "Detroit", sport_id: 5 })
t83 = Team.create({ name: "Canucks", city: "Vancouver", sport_id: 5 })
t84 = Team.create({ name: "Blackhawks", city: "Chicago", sport_id: 5 })

t85 = Team.create({ name: "Woods", city: "Tiger", sport_id: 6 })
t86 = Team.create({ name: "Mcilroy", city: "Rory", sport_id: 6 })
t87 = Team.create({ name: "Watson", city: "Bubba", sport_id: 6 })
t88 = Team.create({ name: "Smith", city: "Kyle", sport_id: 6 })
t89 = Team.create({ name: "Mickelson", city: "Phil", sport_id: 6 })
t90 = Team.create({ name: "Nicklaus", city: "Jack", sport_id: 6 })

t91 = Team.create({ name: "Mountain", city: "The", sport_id: 7 })
t92 = Team.create({ name: "Oberyn", city: "Prince", sport_id: 7 })

t93 = Team.create({ name: "Diaz", city: "Nick", sport_id: 8 })
t94 = Team.create({ name: "Tyson", city: "Mike", sport_id: 8 })
t95 = Team.create({ name: " ", city: "Jeff", sport_id: 8 })
t96 = Team.create({ name: " ", city: "CJ", sport_id: 8 })


g1  = Game.create({ team1_id:  1, team2_id:  21, day_id: 1, odds: 0.4, sport_id: 1 })
g2  = Game.create({ team1_id:  5, team2_id:  19, day_id: 1, odds: 0.9, sport_id: 1 })
g3  = Game.create({ team1_id:  22, team2_id:  6, day_id: 1, odds: 0.3, sport_id: 1 })
g4  = Game.create({ team1_id:  7, team2_id:  8, day_id: 1, odds: 0.4, sport_id: 1 })
g5  = Game.create({ team1_id:  9, team2_id: 10, day_id: 1, odds: 0.5, sport_id: 1 })
g6  = Game.create({ team1_id: 11, team2_id: 16, day_id: 1, odds: 0.6, sport_id: 1 })
g7  = Game.create({ team1_id: 12, team2_id: 17, day_id: 1, odds: 0.7, sport_id: 1 })
g8  = Game.create({ team1_id: 13, team2_id: 18, day_id: 1, odds: 0.8, sport_id: 1 })
g9  = Game.create({ team1_id: 14, team2_id: 30, day_id: 1, odds: 0.9, sport_id: 1 })

g11  = Game.create({ team1_id: 31, team2_id: 32, day_id: 1, odds: 0.2, sport_id: 2 })
g12  = Game.create({ team1_id: 33, team2_id: 34, day_id: 2, odds: 0.52, sport_id: 2 })
g13  = Game.create({ team1_id: 35, team2_id: 36, day_id: 2, odds: 0.56, sport_id: 2 })
g14  = Game.create({ team1_id: 37, team2_id: 38, day_id: 2, odds: 0.43, sport_id: 2 })
g15  = Game.create({ team1_id: 39, team2_id: 40, day_id: 2, odds: 0.67, sport_id: 2 })
g16  = Game.create({ team1_id: 41, team2_id: 42, day_id: 2, odds: 0.29, sport_id: 2 })
g17  = Game.create({ team1_id: 43, team2_id: 44, day_id: 2, odds: 0.39, sport_id: 2 })
g18  = Game.create({ team1_id: 45, team2_id: 46, day_id: 2, odds: 0.4, sport_id: 2 })

g19 = Game.create({ team1_id: 63, team2_id: 65, day_id: 1, odds: 0.25, sport_id: 3 })
g20 = Game.create({ team1_id: 64, team2_id: 66, day_id: 2, odds: 0.75, sport_id: 3 })
g21 = Game.create({ team1_id: 67, team2_id: 68, day_id: 2, odds: 0.55, sport_id: 3 })
g22 = Game.create({ team1_id: 69, team2_id: 70, day_id: 2, odds: 0.65, sport_id: 3 })
g23 = Game.create({ team1_id: 71, team2_id: 72, day_id: 2, odds: 0.45, sport_id: 3 })

g24 = Game.create({ team1_id: 73, team2_id: 74, day_id: 1, odds: 0.25, sport_id: 4 })
g25 = Game.create({ team1_id: 75, team2_id: 76, day_id: 2, odds: 0.75, sport_id: 4 })
g26 = Game.create({ team1_id: 77, team2_id: 78, day_id: 2, odds: 0.55, sport_id: 4 })

g27 = Game.create({ team1_id: 79, team2_id: 80, day_id: 1, odds: 0.25, sport_id: 5 })
g28 = Game.create({ team1_id: 81, team2_id: 82, day_id: 2, odds: 0.75, sport_id: 5 })
g29 = Game.create({ team1_id: 83, team2_id: 84, day_id: 2, odds: 0.55, sport_id: 5 })

g30 = Game.create({ team1_id: 85, team2_id: 88, day_id: 1, odds: 0.75, sport_id: 6 })
g31 = Game.create({ team1_id: 86, team2_id: 87, day_id: 2, odds: 0.75, sport_id: 6 })
g32 = Game.create({ team1_id: 89, team2_id: 90, day_id: 2, odds: 0.55, sport_id: 6 })

g33 = Game.create({ team1_id: 91, team2_id: 92, day_id: 1, odds: 0.01, sport_id: 7 })

g34 = Game.create({ team1_id: 93, team2_id: 94, day_id: 1, odds: 0.25, sport_id: 8 })
g35 = Game.create({ team1_id: 95, team2_id: 96, day_id: 2, odds: 0.5, sport_id: 8 })



d1 = Day.create({ user_id: 1, date: Date.today + 1 })
d2 = Day.create({ user_id: 2, date: Date.today + 1 })